services:
  sns_poster_app:
    build: .
    container_name: sns_poster_app
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    env_file:
      - ./backend/.env
    environment:
      - FLASK_DEBUG=1
    restart: unless-stopped
